<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>c172c91c-c444-4525-a4b2-358dc017674c</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..\..</DockerfileContext>
    <DockerComposeProjectPath>..\..\..\docker-compose.dcproj</DockerComposeProjectPath>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="Components\Pages\Registration.razor" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Won.Shared\Won.Shared.csproj" />
    <ProjectReference Include="..\Won.Web.Client\Won.Web.Client.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication" Version="2.3.10" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="8.0.24" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
  </ItemGroup>

</Project>
